name: ubenwa_challenge
description: A new Flutter project for Ubenwa Challenge. This apps calls background service even when the app is closed.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  equatable: ^2.0.3
  bloc_test: ^9.0.3
  formz: ^0.4.1
  email_validator: '^2.1.16'
  flutter_bloc: ^8.0.1
  flutter_switch: ^0.3.2
  connectivity_plus: ^2.3.6
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev
  mocktail: ^0.3.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

